# Directiva
name: Pull request notification
on: pull_request

env: 
    NAME: CodigoFacilito

jobs:
    first_jobs:
        runs-on: ubuntu-latest
        
        outputs:
            salida: hola
            salida2: ${{ steps.step_1.outputs.my_variable }}

        steps:
            - name: "Hola mundo"
              id: step_1
              run: | 
                echo "Hola mundo $NAME"
                echo "Hola mundo $GITHUB_OUTPUT"
                echo "my_variable=Hola Mundo >> $GITHUB_OUTPUT
                echo "$GITHUB_OUTPUT"
                echo ${{ steps.step_1.outputs.my_variable }}

          

    second_jobs:
        #if: false

        env:
            SALIDA: ${{needs.first_jobs.outputs.salida2}}

        needs:
            - first_jobs
            
        runs-on: ubuntu-latest

        steps:
            - name: Segundo trabajo
              run: echo "Ejecutar segundo hola mundo $SALIDA"

